{% set version = "8.0.4" %}

package:
  name: thinc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/thinc/thinc-{{ version }}.tar.gz
  sha256: 32016a5be62a2c4b5f86954ae30f8da78bacaa5966ea3ce56886cf9d7c7dcbe6
  patches: patches/0001-importorskip-tests.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win and py27]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - cython
    - python
    - pip
    - numpy
    - setuptools
    - wheel
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - murmurhash >=0.28.0,<1.1.0
    - cython-blis >=0.4.0,<0.8.0
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - murmurhash >=0.28.0,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - cython-blis >=0.4.0,<0.8.0
    - wasabi >=0.4.0,<1.1.0
    - srsly >=2.0.0,<3.0.0
    - catalogue >=2.0.3,<3.0.0
    - pydantic >=1.7.1,<1.8.0
    - dataclasses >=0.6,<1.0  # [py36]
    - typing_extensions >=3.7.4.1,<4.0.0.0  # [py36 or py37]
    - contextvars >=2.4,<3  # [py36]

test:
  requires:
    - hypothesis
    - importlib-metadata ==3.3.0  # [py<38]
    - pytest
    - mock
    - pathy >=0.3.5
  imports:
    - thinc
    - thinc.api
    - thinc.linear
    - thinc.extra
    - thinc.neural

  commands:
    - python -m pytest --tb=native --pyargs thinc

about:
  home: https://github.com/explosion/thinc/
  license: MIT
  license_file: LICENSE
  summary: 'thinc: a lightweight deep learning library'
  description: |
    A refreshing functional take on deep learning, compatible with your
    favorite libraries

extra:
  recipe-maintainers:
    - rmax
    - honnibal
    - ines
    - adrianeboyd
